# Generated by Django 4.0.2 on 2022-02-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('image_product', models.ImageField(blank=True, null=True, upload_to='media/products/')),
            ],
        ),
    ]
