# Generated by Django 4.0.2 on 2022-03-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_category', '0003_remove_product_image_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание продукта'),
        ),
    ]
