# Generated by Django 4.0.2 on 2022-03-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_category', '0004_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price'),
        ),
    ]
